<?php

namespace App\Services;

use App\Models\Website;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Process;

class Pm2Service
{
    protected bool $isLocal;
    protected string $pm2ConfigPath;

    public function __construct()
    {
        $this->isLocal = in_array(config('app.env'), ['local', 'dev', 'development']);
        
        // Environment-aware paths
        if ($this->isLocal) {
            $this->pm2ConfigPath = storage_path('server/pm2');
        } else {
            $this->pm2ConfigPath = '/etc/pm2';
        }
    }

    /**
     * Generate PM2 ecosystem configuration.
     *
     * @param Website $website The website to generate config for
     * @return string The generated ecosystem configuration
     * @throws \InvalidArgumentException If website is not a Node.js project
     */
    public function generateEcosystemConfig(Website $website): string
    {
        if ($website->project_type !== 'node') {
            throw new \InvalidArgumentException('PM2 configuration is only for Node.js projects');
        }

        $appName = str_replace('.', '-', $website->domain);
        $nodeVersion = $website->node_version ?? '20';
        $port = $website->port ?? 3000;
        $instances = 'max'; // Auto-scale based on CPU cores
        
        // Determine root path based on environment
        if ($this->isLocal) {
            $appPath = storage_path("server/www/{$website->domain}");
        } else {
            $appPath = $website->root_path;
        }
        
        // Log paths
        if ($this->isLocal) {
            $errorLog = storage_path("server/logs/pm2/{$appName}-error.log");
            $outLog = storage_path("server/logs/pm2/{$appName}-out.log");
        } else {
            $errorLog = "/var/log/pm2/{$appName}-error.log";
            $outLog = "/var/log/pm2/{$appName}-out.log";
        }

        return <<<JS
// PM2 Ecosystem Configuration for {$website->domain}
// Generated by Hostiqo
// Node.js version: {$nodeVersion}

module.exports = {
  apps: [{
    name: '{$appName}',
    script: 'index.js',  // Update to your entry point (server.js, app.js, etc.)
    cwd: '{$appPath}',
    
    // Execution mode
    instances: '{$instances}',
    exec_mode: 'cluster',
    
    // Node.js interpreter
    interpreter: 'node',
    // For NVM users, uncomment and update path:
    // interpreter: '/home/deploy/.nvm/versions/node/v{$nodeVersion}.0/bin/node',
    
    // Environment variables
    env: {
      NODE_ENV: 'production',
      PORT: {$port}
    },
    
    // Logging
    error_file: '{$errorLog}',
    out_file: '{$outLog}',
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    merge_logs: true,
    
    // Restart behavior
    autorestart: true,
    watch: false,
    max_memory_restart: '1G',
    
    // Advanced options
    kill_timeout: 5000,
    wait_ready: true,
    listen_timeout: 10000
  }]
};

JS;
    }

    /**
     * Write PM2 ecosystem configuration file.
     *
     * @param Website $website The website to write config for
     * @return array{success: bool, filepath?: string, message?: string, error?: string}
     */
    public function writeEcosystemConfig(Website $website): array
    {
        try {
            if ($website->project_type !== 'node') {
                return [
                    'success' => true,
                    'message' => 'Not a Node.js project, skipping PM2 configuration'
                ];
            }

            $config = $this->generateEcosystemConfig($website);
            $appName = str_replace('.', '-', $website->domain);
            $filename = "ecosystem.{$appName}.config.js";
            $filepath = "{$this->pm2ConfigPath}/{$filename}";

            if ($this->isLocal) {
                // Local mode: Direct file write
                // Create directories
                if (!File::exists($this->pm2ConfigPath)) {
                    File::makeDirectory($this->pm2ConfigPath, 0755, true);
                }
                
                $logDir = storage_path('server/logs/pm2');
                if (!File::exists($logDir)) {
                    File::makeDirectory($logDir, 0755, true);
                }
                
                // Write config
                File::put($filepath, $config);
                
                Log::info('[LOCAL] PM2 ecosystem config written to storage', [
                    'filepath' => $filepath,
                    'website_id' => $website->id
                ]);
            } else {
                // Production mode: Use sudo
                $tempFile = tempnam(sys_get_temp_dir(), 'pm2_');
                File::put($tempFile, $config);

                // Create PM2 config directory if not exists
                if (!File::exists($this->pm2ConfigPath)) {
                    Process::run("sudo /bin/mkdir -p {$this->pm2ConfigPath}");
                    Process::run("sudo /bin/chmod 755 {$this->pm2ConfigPath}");
                }

                // Move to PM2 directory with sudo
                $result = Process::run("sudo /bin/cp {$tempFile} {$filepath}");
                
                // Clean up temp file
                @unlink($tempFile);
                
                if ($result->failed()) {
                    throw new \Exception("Failed to write PM2 config: " . $result->errorOutput());
                }

                // Set proper permissions
                Process::run("sudo /bin/chmod 644 {$filepath}");
                
                Log::info('[PRODUCTION] PM2 ecosystem config created', [
                    'filepath' => $filepath,
                    'website_id' => $website->id
                ]);
            }

            return [
                'success' => true,
                'filepath' => $filepath,
                'message' => 'PM2 ecosystem configuration created successfully'
            ];
        } catch (\Exception $e) {
            Log::error('Failed to write PM2 ecosystem config', [
                'website_id' => $website->id,
                'error' => $e->getMessage()
            ]);

            return [
                'success' => false,
                'error' => $e->getMessage()
            ];
        }
    }

    /**
     * Delete PM2 ecosystem configuration.
     *
     * @param Website $website The website to delete config for
     * @return array{success: bool, message?: string, error?: string}
     */
    public function deleteEcosystemConfig(Website $website): array
    {
        try {
            $appName = str_replace('.', '-', $website->domain);
            $filename = "ecosystem.{$appName}.config.js";
            $filepath = "{$this->pm2ConfigPath}/{$filename}";

            if ($this->isLocal) {
                if (File::exists($filepath)) {
                    File::delete($filepath);
                }
            } else {
                Process::run("sudo /bin/rm -f {$filepath}");
            }

            return [
                'success' => true,
                'message' => 'PM2 ecosystem configuration deleted'
            ];
        } catch (\Exception $e) {
            Log::error('Failed to delete PM2 ecosystem config', [
                'website_id' => $website->id,
                'error' => $e->getMessage()
            ]);

            return [
                'success' => false,
                'error' => $e->getMessage()
            ];
        }
    }

    /**
     * Start PM2 application.
     *
     * @param Website $website The website to start
     * @return array{success: bool, message?: string, error?: string}
     */
    public function startApp(Website $website): array
    {
        try {
            if ($website->project_type !== 'node') {
                return [
                    'success' => false,
                    'error' => 'Not a Node.js project'
                ];
            }

            if ($this->isLocal) {
                return [
                    'success' => false,
                    'error' => 'PM2 control not available in local mode. Use post-deploy script in webhook instead.'
                ];
            }

            $appName = str_replace('.', '-', $website->domain);
            $configPath = "{$this->pm2ConfigPath}/ecosystem.{$appName}.config.js";

            // Try to restart first (if already exists), otherwise start
            $result = Process::run("pm2 restart {$appName} --update-env 2>/dev/null || pm2 start {$configPath}");

            if ($result->successful()) {
                Process::run("pm2 save");
                
                $website->update(['pm2_status' => 'running']);
                
                Log::info('PM2 app started', [
                    'website_id' => $website->id,
                    'app_name' => $appName
                ]);

                return [
                    'success' => true,
                    'message' => 'Application started successfully'
                ];
            }

            return [
                'success' => false,
                'error' => $result->errorOutput()
            ];
        } catch (\Exception $e) {
            Log::error('Failed to start PM2 app', [
                'website_id' => $website->id,
                'error' => $e->getMessage()
            ]);

            return [
                'success' => false,
                'error' => $e->getMessage()
            ];
        }
    }

    /**
     * Stop PM2 application.
     *
     * @param Website $website The website to stop
     * @return array{success: bool, message?: string, error?: string}
     */
    public function stopApp(Website $website): array
    {
        try {
            if ($website->project_type !== 'node') {
                return [
                    'success' => false,
                    'error' => 'Not a Node.js project'
                ];
            }

            if ($this->isLocal) {
                return [
                    'success' => false,
                    'error' => 'PM2 control not available in local mode'
                ];
            }

            $appName = str_replace('.', '-', $website->domain);
            $result = Process::run("pm2 stop {$appName}");

            if ($result->successful()) {
                Process::run("pm2 save");
                
                $website->update(['pm2_status' => 'stopped']);
                
                Log::info('PM2 app stopped', [
                    'website_id' => $website->id,
                    'app_name' => $appName
                ]);

                return [
                    'success' => true,
                    'message' => 'Application stopped successfully'
                ];
            }

            return [
                'success' => false,
                'error' => $result->errorOutput()
            ];
        } catch (\Exception $e) {
            Log::error('Failed to stop PM2 app', [
                'website_id' => $website->id,
                'error' => $e->getMessage()
            ]);

            return [
                'success' => false,
                'error' => $e->getMessage()
            ];
        }
    }

    /**
     * Restart PM2 application.
     *
     * @param Website $website The website to restart
     * @return array{success: bool, message?: string, error?: string}
     */
    public function restartApp(Website $website): array
    {
        try {
            if ($website->project_type !== 'node') {
                return [
                    'success' => false,
                    'error' => 'Not a Node.js project'
                ];
            }

            if ($this->isLocal) {
                return [
                    'success' => false,
                    'error' => 'PM2 control not available in local mode'
                ];
            }

            $appName = str_replace('.', '-', $website->domain);
            $result = Process::run("pm2 restart {$appName} --update-env");

            if ($result->successful()) {
                Process::run("pm2 save");
                
                $website->update(['pm2_status' => 'running']);
                
                Log::info('PM2 app restarted', [
                    'website_id' => $website->id,
                    'app_name' => $appName
                ]);

                return [
                    'success' => true,
                    'message' => 'Application restarted successfully'
                ];
            }

            return [
                'success' => false,
                'error' => $result->errorOutput()
            ];
        } catch (\Exception $e) {
            Log::error('Failed to restart PM2 app', [
                'website_id' => $website->id,
                'error' => $e->getMessage()
            ]);

            $website->update(['pm2_status' => 'error']);

            return [
                'success' => false,
                'error' => $e->getMessage()
            ];
        }
    }

    /**
     * Get PM2 app status.
     *
     * @param Website $website The website to check status for
     * @return array{success: bool, status?: string, message?: string, error?: string, pid?: int|null, uptime?: int|null, restarts?: int, memory?: int, cpu?: int}
     */
    public function getAppStatus(Website $website): array
    {
        try {
            $appName = str_replace('.', '-', $website->domain);
            
            // This is for production mode only
            if ($this->isLocal) {
                return [
                    'success' => true,
                    'message' => 'PM2 status not available in local mode',
                    'status' => 'local'
                ];
            }
            
            $result = Process::run("pm2 jlist");
            
            if ($result->failed()) {
                return [
                    'success' => false,
                    'error' => 'PM2 not available or not running'
                ];
            }

            $processes = json_decode($result->output(), true);
            
            foreach ($processes as $process) {
                if ($process['name'] === $appName) {
                    return [
                        'success' => true,
                        'status' => $process['pm2_env']['status'] ?? 'unknown',
                        'pid' => $process['pid'] ?? null,
                        'uptime' => $process['pm2_env']['pm_uptime'] ?? null,
                        'restarts' => $process['pm2_env']['restart_time'] ?? 0,
                        'memory' => $process['monit']['memory'] ?? 0,
                        'cpu' => $process['monit']['cpu'] ?? 0
                    ];
                }
            }

            return [
                'success' => true,
                'status' => 'not_running',
                'message' => 'App not found in PM2 process list'
            ];
        } catch (\Exception $e) {
            return [
                'success' => false,
                'error' => $e->getMessage()
            ];
        }
    }
}
